/*Связь между контрактами и способами распространения должна
 указывать на связь контрактов и услуг вместо контрактов. 
*/
ALTER TABLE CONTRACT_SHIPMENTS DROP CONTRACT_ID;
ALTER TABLE CONTRACT_SHIPMENTS ADD CO_SERV_ID INTEGER NOT NULL;
ALTER TABLE CONTRACT_SHIPMENTS ADD CONSTRAINT FK_CONTRACT_SHIPMENTS_1
FOREIGN KEY (CO_SERV_ID) REFERENCES CONTRACT_SERVICES(CO_SERV_ID);

/*
Ввести учет рекламных носителей. 
*/
CREATE TABLE MEDIUMS (
    MEDIUM_ID  INTEGER NOT NULL,
    "TYPE"     VARCHAR(20) NOT NULL
);
ALTER TABLE MEDIUMS ADD CONSTRAINT PK_MEDIUMS PRIMARY KEY (MEDIUM_ID);


/*
В таблице расписания сделать ссылку на рекламный носитель и явно указать период аренды. 
*/
ALTER TABLE TIMETABLE DROP PERIOD;
ALTER TABLE TIMETABLE ADD MEDIUM_ID INTEGER NOT NULL;
ALTER TABLE TIMETABLE ADD CONSTRAINT FK_TIMETABLE_1
FOREIGN KEY (MEDIUM_ID) REFERENCES MEDIUMS(MEDIUM_ID);
ALTER TABLE TIMETABLE ADD INITIAL_DATE TIMESTAMP NOT NULL;
ALTER TABLE TIMETABLE ADD FINAL_DATE TIMESTAMP NOT NULL;

