/* If database already exists drop it.  */
CONNECT 'tiger.ftk.spbstu.ru:/var/lib/firebird/435013/adagency.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

DROP DATABASE;

/* Create database and connect.  */
CREATE DATABASE 'tiger.ftk.spbstu.ru:/var/lib/firebird/435013/adagency.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

CONNECT 'tiger.ftk.spbstu.ru:/var/lib/firebird/435013/adagency.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

/* Set charset.  */
SET NAMES CYRL;

/* create tables. */
CREATE TABLE CLIENTS (
    	CLIENT_ID 	INTEGER NOT NULL,
		DATA 		VARCHAR(30) NOT NULL,
CONSTRAINT	PK_CLIENTS PRIMARY KEY (CLIENT_ID)
);
COMMIT;

CREATE TABLE TIMETABLE (
    	TIME_ID  INTEGER NOT NULL,
    	PERIOD   INTEGER NOT NULL,
    	DECIMAL(12,2) NOT NULL,
	CONSTRAINT PK_TIMETABLE PRIMARY KEY (TIME_ID)
);
COMMIT;

CREATE TABLE CONTRACTS (
    	CONTRACT_ID	 INTEGER NOT NULL,
    	CLIENT_ID    INTEGER NOT NULL REFERENCES CLIENTS
		TIME_ID      INTEGER NOT NULL REFERENCES TIMETABLE,
		DECIMAL(12,2) NOT NULL,
		CONSTRAINT PK_CONTRACTS PRIMARY KEY (CONTRACT_ID)
);
COMMIT;


CREATE TABLE SERVICES (
     	SERVICE_ID  INTEGER NOT NULL,
     	"TYPE"      VARCHAR(10) NOT NULL,     	
     	QUANTITY    INTEGER NOT NULL,
	DECIMAL(12,2) NOT NULL,
	CONSTRAINT PK_SERVICES PRIMARY KEY (SERVICE_ID)
);
COMMIT;

CREATE TABLE CONTRACT_SERVICES (
    	CO_SERV_ID   INTEGER NOT NULL,
    	CONTRACT_ID  INTEGER NOT NULL REFERENCES CONTRACTS,
    	SERVICE_ID   INTEGER NOT NULL REFERENCES SERVICES,	
	CONSTRAINT PK_CONTRACT_SERVICES PRIMARY KEY (CO_SERV_ID)
);
COMMIT;

CREATE TABLE SHIPMENT (
    	SHIPMENT_ID  INTEGER NOT NULL,
    	"TYPE"       VARCHAR(25) NOT NULL,
	DECIMAL(12,2) NOT NULL,    	
	CONSTRAINT PK_SHIPMENT PRIMARY KEY (SHIPMENT_ID) 
);
COMMIT;

CREATE TABLE CONTRACT_SHIPMENTS (
    	CO_SHIP_ID   INTEGER NOT NULL,
   	CONTRACT_ID  INTEGER NOT NULL REFERENCES CONTRACTS,
    	SHIPMENT_ID  INTEGER NOT NULL REFERENCES SHIPMENT,
	CONSTRAINT PK_CONTRACT_SHIPMENTS PRIMARY KEY (CO_SHIP_ID)
);
COMMIT;
